### ISSUE TITLE
Can't build on node 0.10.22

### ISSUE THREAD

**Issue by nleush** [superfeedr/superfeedr-node#17]

**Comment by julien51** [comment]
Any error?

**Comment by nleush** [comment]
Looks like problem was with node-stringprep building.

Tried (from https://github.com/node-xmpp/node-stringprep/issues/32):

```
sudo apt-get install libicu-dev
```

That helped.

Original error was:

```
> node-stringprep@0.1.8 install /tmp/node_modules/superfeedr/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/superfeedr/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/build'
  CXX(target) Release/obj.target/node_stringprep/node-stringprep.o
../node-stringprep.cc:3:28: fatal error: unicode/unistr.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/node_stringprep/node-stringprep.o] Error 1
make: Leaving directory `/tmp/node_modules/superfeedr/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/v0.10.22/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.2.0-54-virtual
gyp ERR! command "node" "/home/ubuntu/.nvm/v0.10.22/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/superfeedr/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok 
```

**Comment by julien51** [comment]
Thanks! I'll keep track of that.
